### ISSUE TITLE
extra columns in csv dictionary not being dealt with

### ISSUE THREAD

**Issue by rkiddy** [rkiddy/ca_hhs#17]
The pull from a csv file to a dictionary will, at times, have extra columns. These are put into a list (I think it is a list) but the dictionary key of None (the python None value).

When this gets put into a table, it looks like this:

```
mysql> select * from wic_authorized_vendors where latitude like 'Lo%' \G
*************************** 1. row ***************************
        vendor: CARNICERIA LA OAXAQUENA #01                                                                                                                                                                             
       address: 200 EAST PACIFIC COAST HWY                                                                                     
second_address: NULL
          city:                                                            
           zip: Long Beach                                                  
        county: 90806
      latitude: Los Angeles                                                 
     longitude: 33.78971000
          None: NULL
1 row in set (0.01 sec)
```

There are several things I can do here. Which of them are smarter?
